# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = false

[cmd_duration]
min_time = 10_000
show_milliseconds = false
format = "took [$duration]($style) "

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[X](bold red)"  
vicmd_symbol = "[â®](bold green)"

[git_branch]
style = "bold purple"
truncation_length = 16

[git_status]
modified.enabled = true
modified.style = "bold purple"
conflicted.enabled = true
conflicted.style = "yellow"
stashed.enabled = true
stashed.style = "bold blue"
deleted.enabled = true
deleted.style = "white"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
untracked.enabled = true
untracked.style = "green"
renamed.enabled = true
renamed.style = "bold cyan"
staged.enabled = true
staged.style = "cyan"


#[time]
#disabled = true
#format = "[$time]($style) "
#style = "212"

[directory]
truncation_length = 2
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_symbol = "â€¦"
truncate_to_repo = true
style = "bold green"

[username]
disabled = true

# These symbols will only show when battery levels are 20% or less
[battery]
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]  # "bold red" style when capacity is between 0% and 20%
threshold = 20
style = "bold red"

# Clear visibility for exit codes
[status]
style = "bg:red"
symbol = "ğŸ’£ "
format = '[\[$symbol$status\]]($style) '
disabled = false
