# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 1000

[line_break]
disabled = false

[cmd_duration]
min_time = 10_000
show_milliseconds = false
format = "[$duration]($style) "

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold green)"

[git_branch]
style = "bold purple"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

#[time]
#disabled = true
#format = "[$time]($style) "
#style = "212"

[directory]
truncation_length = 10
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_symbol = ".."
truncate_to_repo = true
style = "bold green"

[username]
disabled = true

[hostname]
disabled = true

# These symbols will only show when battery levels are 20% or less
[battery]
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]  # "bold red" style when capacity is between 0% and 20%
threshold = 20
style = "bold red"

[aws]
disabled= false

# Clear visibility for exit codes
# [status]
# style = "bg:red"
# format = '($style)'
# disabled = false
